### ISSUE TITLE
build on Raspberry Pi

### ISSUE THREAD

**Issue by jgastonraoul** [moddevices/max-gen-skeleton#1]
Hi !

I'd like to build LV2 plugins on Raspberry Pi using your project.
It works well on Mac, but on my Pi, I have the following errors : 
`make all -C source
make[1]: Entering directory '/home/raspberry/max-gen-skeleton/source'
g++ DistrhoPluginMaxGen.cpp -Wall -Wextra -pipe -fPIC -DPIC -DNDEBUG -O3 -ffast-math -mtune=generic -msse -msse2 -fdata-sections -ffunction-sections -mfpmath=sse -fvisibility=hidden -DHAVE_JACK -std=c++0x -std=gnu++0x -fvisibility-inlines-hidden  -I. -Idpf/distrho -Igen_dsp -I../plugin -Wno-unused-parameter -DGENLIB_USE_FASTMATH -DGENLIB_USE_FLOAT32 -DGENLIB_USE_JSON=0 -MD -MP -c -o DistrhoPluginMaxGen.cpp.o
g++: error: unrecognized argument in option ‘-mtune=generic’
g++: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a17 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a72 cortex-a72.cortex-a53 cortex-a8 cortex-a9 cortex-m0 cortex-m0.small-multiply cortex-m0plus cortex-m0plus.small-multiply cortex-m1 cortex-m1.small-multiply cortex-m3 cortex-m4 cortex-m7 cortex-r4 cortex-r4f cortex-r5 cortex-r7 cortex-r8 ep9312 exynos-m1 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native qdf24xx strongarm strongarm110 strongarm1100 strongarm1110 xgene1 xscale
g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++: error: unrecognized command line option ‘-msse2’
g++: error: unrecognized command line option ‘-mfpmath=sse’
Makefile:154: recipe for target 'DistrhoPluginMaxGen.cpp.o' failed
make[1]: *** [DistrhoPluginMaxGen.cpp.o] Error 1
make[1]: Leaving directory '/home/raspberry/max-gen-skeleton/source'
Makefile:35: recipe for target 'plugin' failed
make: *** [plugin] Error 2`

Any idea ?

**Comment by falkTX** [comment]
Just use `make NOOPT=true`

**Comment by jgastonraoul** [comment]
It works perfectly, thanks !
The only other thing I had to do was to recompile lv2-ttl-generator for the Pi.
